# Generated by Django 5.0.1 on 2024-01-07 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Mapapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='polygon',
            name='leafletId',
        ),
    ]
