# Generated by Django 5.0.1 on 2024-01-09 05:11

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Mapapp', '0002_remove_polygon_leafletid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='polygon',
            name='points',
        ),
        migrations.DeleteModel(
            name='Points',
        ),
        migrations.AddField(
            model_name='polygon',
            name='points',
            field=django.contrib.gis.db.models.fields.PolygonField(blank=True, null=True, srid=4326),
        ),
    ]
