# Generated by Django 5.0.1 on 2024-01-09 05:12

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Mapapp', '0003_remove_polygon_points_delete_points_polygon_points'),
    ]

    operations = [
        migrations.AlterField(
            model_name='polygon',
            name='points',
            field=django.contrib.gis.db.models.fields.PolygonField(srid=4326),
        ),
    ]
