# Generated by Django 5.0.1 on 2024-01-11 10:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mapapp', '0006_customerpolygon'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerpolygon',
            name='polygon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Mapapp.polygon'),
        ),
    ]
