# Generated by Django 5.0.1 on 2024-01-12 02:41

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mapapp', '0007_customerpolygon_polygon'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('polygon', django.contrib.gis.db.models.fields.PolygonField(srid=4326)),
            ],
        ),
        migrations.DeleteModel(
            name='CustomerPolygon',
        ),
        migrations.DeleteModel(
            name='Polygon',
        ),
    ]
