# Generated by Django 5.0.1 on 2024-01-20 15:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mapapp', '0008_servicearea_delete_customerpolygon_delete_polygon'),
        ('alertapp', '0002_alter_alertmodel_alert_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alertservicemodel',
            name='service_address',
        ),
        migrations.AddField(
            model_name='alertservicemodel',
            name='service_area',
            field=models.ForeignKey(default=10000, on_delete=django.db.models.deletion.CASCADE, to='Mapapp.servicearea'),
            preserve_default=False,
        ),
    ]
